### ISSUE TITLE
"Internal Server Error: error" - 

### ISSUE THREAD

**Issue by AlexIzydorczyk** [ipselon/react-ui-builder#24]
Hi

I just installed react-ui-builder with:

```
sudo npm install react-ui-builder -g
```

And am getting:
```
"Internal Server Error: error"

```
on http://127.0.0.1:2222/builder/

It appears to have installed correctly though. Any ideas how to debug or what might be wrong?

Install logs: 
```
> ws@0.5.0 install /usr/local/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> fsevents@0.3.6 install /usr/local/lib/node_modules/react-ui-builder/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> ws@0.4.31 install /usr/local/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/usr/local/bin/react-ui-builder -> /usr/local/lib/node_modules/react-ui-builder/react-ui-builder.js
```

Thanks,
Alex

--EDIT--

It appears that accessing react-ui-builder from:

http://127.0.0.1:2222/builder/ throws this error

but accessing it from

http://localhost:2222/builder/ does not.

This also means that accessing it remotely (I had tried to run it in a docker container on an EC2 instance) does not work.

**Comment by ipselon** [comment]
Did you start builder with sudo ?

**Comment by ipselon** [comment]
I fixed this issue. Now you can get access to builder which is started remotely. But remember that builder works with project in local folder - on the host where it was started.

**Comment by AlexIzydorczyk** [comment]
Apologies for the slow response - it does indeed work now. Thank you for fixing this.

**Comment by bb78657** [comment]
I installed react today on Linux:
sudo npm install react-ui-builder -g
I then ran sudo react-ui-builder
and receive the same "Internal Server Error: error" on http://localhost:2222/builder/

**Comment by ipselon** [comment]
@bb78657 please use Structor (https://github.com/ipselon/structor) instead of react-ui-builder

**Comment by bb78657** [comment]
Thanks for the quick response.
I installed structor and started but got the following on pointing my browser to http://localhost:2222/structor/  :

Structor started successfully.
Please go to http://localhost:2222/structor
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/FileManager.js:1:4416)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/StorageManager.js:1:8344)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/api.js:1:4064)
    at /usr/local/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/local/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/Client.js:1:1453)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/ClientManager.js:1:1506)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/api.js:1:4449)
    at /usr/local/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/local/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
ReferenceError: Promise is not defined
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/FileManager.js:1:4704)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/StorageManager.js:1:1680)
    at e._createClass.value (/usr/local/lib/node_modules/structor/server/api.js:1:5012)
    at /usr/local/lib/node_modules/structor/server/api.js:1:3507
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/structor/node_modules/express/lib/router/route.js:131:13)
    at /usr/local/lib/node_modules/structor/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/structor/node_modules/body-parser/node_modules/raw-body/index.js:308:7)

**Comment by ipselon** [comment]
For Structor issues please use its repo. 
As for this issue, please upgrade your node.js
